# Generated by Django 5.0.4 on 2024-05-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_headerpages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderPages',
        ),
    ]
